export const certificates = [
  {
    title: "Microsoft Azure Data Scientist Associate",
    issuer: "Microsoft via Coursera",
    date: "Jul 29, 2025",
    description: "Validated expertise in designing and implementing data science solutions using Microsoft Azure.",
    image: "certificates/mc1.png",
    link: "https://www.coursera.org/account/accomplishments/specialization/certificate/TYJQUMTWF90M",
  },
  {
    title: "Perform data science with Azure Databricks",
    issuer: "Microsoft via Coursera",
    date: "Jul 29, 2025",
    description: "Fundamental skills in data analytics and processing using Azure Databricks platform.",
    image: "certificates/mc2.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/GWHBV6Z3H0HB",
  },
  {
    title: "Build and Operate Machine Learning Solutions with Azure",
    issuer: "Microsoft via Coursera",
    date: "Jul 29, 2025",
    description: "Practical knowledge in developing and deploying machine learning models on Azure.",
    image: "certificates/mc3.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/BVSUFCWVX4LU",
  },
  {
    title: "Prepare for DP-100: Data Science on Microsoft Azure Exam",
    issuer: "Microsoft via Coursera",
    date: "Jul 28, 2025",
    description: "Comprehensive preparation for the DP-100 certification exam focused on Azure data science solutions.",
    image: "certificates/mc4.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/YCS1A3WGG36A",
  },
  {
    title: "Microsoft Azure Machine Learning for Data Scientists",
    issuer: "Microsoft via Coursera",
    date: "Jul 22, 2025",
    description: "Core concepts and techniques for machine learning using Microsoft Azure services.",
    image: "certificates/mc5.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/OGDUOV2LI5K0",
  },
  {
    title: "Create Machine Learning Models in Microsoft Azure",
    issuer: "Microsoft via Coursera",
    date: "Jul 22, 2025",
    description: "Hands-on experience in building and deploying machine learning models with Azure tools.",
    image: "certificates/mc6.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/0CXJZKZOXNY2",
  },
  {
    title: "IBM Data Analyst",
    issuer: "IBM via Coursera",
    date: "Jun 25, 2025",
    description: "Understands the core principles of data analysis.",
    image: "certificates/IBM12.jpg",
    link: "https://www.coursera.org/account/accomplishments/specialization/certificate/DEI6GX7JR6C4",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "IBM via Coursera",
    date: "Jun 23, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Excel Basic for Data Analysis",
    issuer: "IBM via Coursera",
    date: "Jun 25, 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM2.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/CN1FE9PMO8SW",
  },
  {
    title: "Data Visualization and Dashboards with Excel and Cognos",
    issuer: "IBM via Coursera",
    date: "Jun 25, 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM3.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/OMCCB8VZW65N",
  },
  {
    title: "Python for Data Science, AI & Development",
    issuer: "IBM via Coursera",
    date: "Jun 23, 2025",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM4.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/R6QD4TS0GKKA",
  },
  {
    title: "Python Project for Data Science",
    issuer: "IBM via Coursera",
    date: "Jun 23, 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM5.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/RK7JCPTE8R4S",
  },
  {
    title: "Databases and SQL for Data Science with Python",
    issuer: "IBM via Coursera",
    date: "Jun 23, 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM6.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/MKTULMCL2ZB0",
  },
  {
    title: "Data Analysis with Python",
    issuer: "IBM via Coursera",
    date: "Jun 25, 2025",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM7.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/S77VIYR2R3JL",
  },
  {
    title: "Data Visualization with Python",
    issuer: "IBM via Coursera",
    date: "Jun 25, 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM8.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/B880P235TSU6",
  },
  {
    title: "IBM Data Analyst Capstone Project",
    issuer: "IBM via Coursera",
    date: "Jun 25, 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM9.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YVR8A0KVD8IB",
  },
  {
    title: "Generative AI: Enhance your Data Analytics Career",
    issuer: "IBM via Coursera",
    date: "Jun 19, 2025",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM10.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/57Z8IQXPHS5T",
  },
  {
    title: "Data Analyst Career Guide and Interview Preparation",
    issuer: "IBM via Coursera",
    date: "Jun 19, 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM11.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/GSRL9EGQJY3F",
  }
];