export const certificates = [
  {
    title: "Microsoft Azure Data Scientist Associate",
    issuer: "Microsoft via Coursera",
    date: "Jul 29, 2025",
    description: "Validated expertise in designing and implementing data science solutions using Microsoft Azure.",
    image: "certificates/mc1.png",
    link: "https://www.coursera.org/account/accomplishments/specialization/certificate/TYJQUMTWF90M",
  },
  {
    title: "Perform data science with Azure Databricks",
    issuer: "Microsoft via Coursera",
    date: "Jul 29, 2025",
    description: "Fundamental skills in data analytics and processing using Azure Databricks platform.",
    image: "certificates/mc2.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/GWHBV6Z3H0HB",
  },
  {
    title: "Build and Operate Machine Learning Solutions with Azure",
    issuer: "Microsoft via Coursera",
    date: "Jul 29, 2025",
    description: "Practical knowledge in developing and deploying machine learning models on Azure.",
    image: "certificates/mc3.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/BVSUFCWVX4LU",
  },
  {
    title: "Prepare for DP-100: Data Science on Microsoft Azure Exam",
    issuer: "Microsoft via Coursera",
    date: "Jul 28, 2025",
    description: "Comprehensive preparation for the DP-100 certification exam focused on Azure data science solutions.",
    image: "certificates/mc4.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/YCS1A3WGG36A",
  },
  {
    title: "Microsoft Azure Machine Learning for Data Scientists",
    issuer: "Microsoft via Coursera",
    date: "Jul 22, 2025",
    description: "Core concepts and techniques for machine learning using Microsoft Azure services.",
    image: "certificates/mc5.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/OGDUOV2LI5K0",
  },
  {
    title: "Create Machine Learning Models in Microsoft Azure",
    issuer: "Microsoft via Coursera",
    date: "Jul 22, 2025",
    description: "Hands-on experience in building and deploying machine learning models with Azure tools.",
    image: "certificates/mc6.png",
    link: "https://www.coursera.org/account/accomplishments/certificate/0CXJZKZOXNY2",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "IBM via Coursera",
    date: "Jun 24, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Excel Basic for Data Analysis",
    issuer: "IBM via Coursera",
    date: "Jul 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM2.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "Data Science Fundamentals",
    issuer: "IBM via Coursera",
    date: "July 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM3.jpg",
    link: "https://dicoding.com/cert/data-science",
  },
  {
    title: "Machine Learning with Python",
    issuer: "IBM via Coursera",
    date: "May 2024",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM4.jpg",
    link: "https://coursera.org/verify/ml-certificate",
  },
  {
    title: "Frontend Developer Bootcamp",
    issuer: "IBM via Coursera",
    date: "Jan 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM5.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "Data Science Fundamentals",
    issuer: "IBM via Coursera",
    date: "July 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM6.jpg",
    link: "https://dicoding.com/cert/data-science",
  },
  {
    title: "Machine Learning with Python",
    issuer: "IBM via Coursera",
    date: "May 2024",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM7.jpg",
    link: "https://coursera.org/verify/ml-certificate",
  },
  {
    title: "Frontend Developer Bootcamp",
    issuer: "IBM via Coursera",
    date: "Jan 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM8.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "Data Science Fundamentals",
    issuer: "IBM via Coursera",
    date: "July 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM9.jpg",
    link: "https://dicoding.com/cert/data-science",
  },
  {
    title: "Machine Learning with Python",
    issuer: "IBM via Coursera",
    date: "May 2024",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM10.jpg",
    link: "https://coursera.org/verify/ml-certificate",
  },
  {
    title: "Frontend Developer Bootcamp",
    issuer: "IBM via Coursera",
    date: "Jan 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM11.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "IBM Data Analyst",
    issuer: "IBM via Coursera",
    date: "Jun 26, 2025",
    description: "Understands the core principles of data analysis.",
    image: "certificates/IBM12.jpg",
    link: "https://www.coursera.org/account/accomplishments/specialization/B5E9RC8KBF3Z",
  },
];