export const certificates = [
  {
    title: "Microsoft Azure Data Scientist Associate",
    issuer: "Microsoft via Coursera",
    date: "July 22, 2025",
    description: "",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/specialization/certificate/TYJQUMTWF90M",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "Microsoft via Coursera",
    date: "June 24, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "Microsoft via Coursera",
    date: "June 24, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "Microsoft via Coursera",
    date: "June 24, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "Microsoft via Coursera",
    date: "June 24, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "Microsoft via Coursera",
    date: "June 24, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Introduction to Data Analytics",
    issuer: "IBM via Coursera",
    date: "June 24, 2025",
    description: "Basic foundamental of data analytics.",
    image: "certificates/IBM1.jpg",
    link: "https://www.coursera.org/account/accomplishments/certificate/YLV5UORSNLMG",
  },
  {
    title: "Excel Basic for Data Analysis",
    issuer: "IBM via Coursera",
    date: "July 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM2.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "Data Science Fundamentals",
    issuer: "IBM via Coursera",
    date: "July 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM3.jpg",
    link: "https://dicoding.com/cert/data-science",
  },
  {
    title: "Machine Learning with Python",
    issuer: "IBM via Coursera",
    date: "May 2024",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM4.jpg",
    link: "https://coursera.org/verify/ml-certificate",
  },
  {
    title: "Frontend Developer Bootcamp",
    issuer: "IBM via Coursera",
    date: "Jan 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM5.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "Data Science Fundamentals",
    issuer: "IBM via Coursera",
    date: "July 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM6.jpg",
    link: "https://dicoding.com/cert/data-science",
  },
  {
    title: "Machine Learning with Python",
    issuer: "IBM via Coursera",
    date: "May 2024",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM7.jpg",
    link: "https://coursera.org/verify/ml-certificate",
  },
  {
    title: "Frontend Developer Bootcamp",
    issuer: "IBM via Coursera",
    date: "Jan 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM8.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "Data Science Fundamentals",
    issuer: "IBM via Coursera",
    date: "July 2025",
    description: "Data wrangling and visualization.",
    image: "certificates/IBM9.jpg",
    link: "https://dicoding.com/cert/data-science",
  },
  {
    title: "Machine Learning with Python",
    issuer: "IBM via Coursera",
    date: "May 2024",
    description: "Strong ML foundations using Python.",
    image: "certificates/IBM10.jpg",
    link: "https://coursera.org/verify/ml-certificate",
  },
  {
    title: "Frontend Developer Bootcamp",
    issuer: "IBM via Coursera",
    date: "Jan 2025",
    description: "Built UI using HTML, CSS, React.",
    image: "certificates/IBM11.jpg",
    link: "https://IBM via Coursera.com/certificate/frontend",
  },
  {
    title: "IBM Data Analyst",
    issuer: "IBM via Coursera",
    date: "June 18, 2025",
    description: "Understands the core principles of data analysis.",
    image: "certificates/IBM12.jpg",
    link: "https://www.coursera.org/account/accomplishments/specialization/B5E9RC8KBF3Z",
  },
];